sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

before_install:
- docker-compose --version
- docker --version
#- docker pull wurstmeister/kafka
#- docker pull spotify/kafka
#- docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 spotify/kafka
script:
- docker ps -a
- docker images
