sudo: required
language: java
jdk: oraclejdk8
script: mvn clean verify
deploy:
  provider: releases
  api_key:
    secure: dJEA4pK1Aie8H+Jw3jdkhKUzkIdWXuHK+AtcLHgCgZTz5mpUWWUEvPxPfOH/j6pXbhFYA5hMGtJp/QftmqKaKkZhzdtfwXyuz9qJTnxomT5LAAbz/w0k2QJCL0FYI4GHwEv9plzelgD5VclEPhurHZjTRtYIybqjFZ0arlnK4M8D191NNGCW7xpa0ocynCioMpBsQOx0VRni1c631HMWL6MUOAsgTOhWekZoA5lyNogx06i8Ea+lSaf9sdYPzeRoNc/hEcDYG3kzyWa326NpQ3r6W3or0QqVCsGECXqm62spUVKLsp5daJc7W0+IDzSxk8fnFyiq1mRqkxfGlakMgnWE5eJYJa9h7Wmeozz9cUhI6sfIYEIssAW5F4jbWbGfKfv+rxnRiPyuXZTUqU/EC/YX7GGd2zqQlgMbv7BfLghoI2Po9SEJT/Y8LJOvIsITr0l43mnoTEndfmQ0aIPVhssol00nVXkcQU5lQPZhfy+ytFL1ZAfbLXO/AFZjqrnhoiZ67quSyQgNjf9s5gmoK1wWDOOEZMVKtNF1eXtfZxGC6l5X9xeiM+jIEuUJh1JwckbF9oDkZP45UrSokg0V3yUMGPVYXZEbsCESw35FfOKCB4Ki+O4yQJkE9LWpJtUBRz9jOJRueS3q1WHwzv85+hBWXdnd/DFNnNdFbYGO2wE=
  file: target/log-tracer.jar
  on:
    repo: DBCDK/log-tracer
